- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'npm_run_package'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false